-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create Users table (VJD)
-- Note: Adjusted to use bigint to match existing database schema (Error 42804)
create table if not exists public."VJD" (
  id bigint primary key generated by default as identity,
  phone_number text unique,
  display_name text,
  avatar text,
  is_locked boolean default false,
  package jsonb default '{"name": "Thành viên mới", "status": "pending", "expiryDate": 0}'::jsonb,
  password text, -- Simple password for demo
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Create Clubs table
create table if not exists public.clubs (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  address text,
  price_range text,
  open_time text default '06:00 - 22:00',
  rating float default 5.0,
  type text default 'daily', -- 'daily' or 'event'
  category_id text default '1',
  distance text default '0km',
  description text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2.1 Create Courts table (Courts belong to Clubs)
create table if not exists public.courts (
  id uuid primary key default uuid_generate_v4(),
  club_id uuid references public.clubs(id) on delete cascade,
  name text not null,
  price_per_hour double precision default 0,
  open_time text default '06:00 - 22:00',
  status text default 'active',
  images text[] default array[]::text[],
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Create Packages table
create table if not exists public.packages (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  duration_months integer default 1,
  price_original double precision default 0,
  price_sale double precision default 0,
  description text,
  features jsonb default '[]'::jsonb,
  is_best_seller boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Create Bookings table
create table if not exists public.bookings (
  id uuid primary key default uuid_generate_v4(),
  user_id bigint references public."VJD"(id), -- Changed to bigint
  date text not null, -- Format YYYY-MM-DD
  slots jsonb default '[]'::jsonb, -- Array of strings e.g. ["07:00", "08:00"]
  court_id text not null, -- Can reference clubs(id) or just text
  total_price double precision default 0,
  status text default 'pending', -- pending, confirmed, cancelled
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. Create Notifications table
create table if not exists public.notifications (
  id uuid primary key default uuid_generate_v4(),
  title text not null,
  content text,
  type text default 'system', -- system, promotion, booking
  date text, -- Display date
  is_read boolean default false,
  user_id bigint, -- Changed to bigint (optional FK)
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. Create System Settings table
create table if not exists public.system_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 7. Insert Initial Data (Optional but recommended)

-- System Settings
insert into public.system_settings (key, value)
values (
  'global_settings', 
  '{"maintenanceMode": false, "homeBanners": ["https://img.freepik.com/free-vector/gradient-sport-facebook-cover-template_23-2149729606.jpg", "https://img.freepik.com/free-vector/flat-design-sport-facebook-cover_23-2149729605.jpg"], "contactPhone": "0901234567"}'::jsonb
)
on conflict (key) do nothing;

-- Sample Packages
insert into public.packages (name, duration_months, price_original, price_sale, description, features, is_best_seller)
values 
('Gói 1 Tháng', 1, 500000, 399000, 'Tập luyện không giới hạn trong 30 ngày', '["Full quyền lợi", "Tủ đồ miễn phí"]'::jsonb, false),
('Gói 3 Tháng', 3, 1500000, 999000, 'Tiết kiệm hơn cho người tập thường xuyên', '["Full quyền lợi", "Tủ đồ miễn phí", "Tặng 1 buổi PT"]'::jsonb, true);

-- Enable RLS (Row Level Security) - Optional for demo but good for security
alter table public."VJD" enable row level security;
create policy "Public access" on public."VJD" for all using (true);

alter table public.clubs enable row level security;
create policy "Public access" on public.clubs for all using (true);

alter table public.packages enable row level security;
create policy "Public access" on public.packages for all using (true);

alter table public.bookings enable row level security;
drop policy if exists "Public access" on public.bookings;
create policy "Public select bookings" on public.bookings for select using (true);
create policy "Public insert bookings" on public.bookings for insert with check (true);
create policy "Public update bookings" on public.bookings for update using (true) with check (true);
create policy "Public delete bookings" on public.bookings for delete using (true);

alter table public.notifications enable row level security;
create policy "Public access" on public.notifications for all using (true);

alter table public.system_settings enable row level security;
create policy "Public access" on public.system_settings for all using (true);
